### ISSUE TITLE
Migrate SMS features from Dynamics to here

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-integration-commons#145]

**Comment by LingForCC** [comment]
ComposeText and MessageSender modules are migrated with #152

**Comment by embbnux** [comment]
MessageStore module is migrated with PR #160

**Comment by embbnux** [comment]
Messages module is migrate with PR #162

**Comment by embbnux** [comment]
Conversation module is migrate with PR #163 
ContactSearch module is last one

**Comment by embbnux** [comment]
ContactSearch module is migrate with PR #164

**Comment by LingForCC** [comment]
All modules are moved. Close the ticket.
