### ISSUE TITLE
Make all integration test Lint compliant

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-integration-commons#198]
Now some of the integration tests are not Lint compliant. We need to adjust them accordingly.

**Comment by LingForCC** [comment]
@embbnux Does the modification of .eslintrc in #210 solve the problem?

**Comment by embbnux** [comment]
I will create a new pr to confirm it in codacy

**Comment by embbnux** [comment]
@LingForCC it solve the problem about no-extraneous-dependencies warning in test file. I test it in #216

**Comment by LingForCC** [comment]
Looks like it works now.
