### ISSUE TITLE
Add Integration Test for number validation of (xxx) xxx-xxxx

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-integration-commons#204]
Needs to consider following numbers
(xxx) xxx-xxxx
(xxx) xxx-xxxx * xxx
(xxx)xxx-xxxx
(xxx)xxx-xxxx * xxx
xxx-xxx-xxxx
xxx-xxx-xxxx * xxx

Need to add test in both SMS and Call

**Comment by LingForCC** [comment]
Integration Test for number validation in Call is implemented with #207

**Comment by embbnux** [comment]
Integration Test for number validation in SMS is implemented with #214 .

**Comment by LingForCC** [comment]
Looks great!
