### ISSUE TITLE
Should not call SMS API request when toNumber is invalid

### ISSUE THREAD

**Issue by marcusrc** [ringcentral/ringcentral-js-integration-commons#205]
Error message seen while running integration test(integration-test/spec-modules/composeText.js):
```
{
"errorCode" : "InvalidParameter",
"message" : "Sending SMS from/to extension numbers is not available",
"errors" : [ {
"errorCode" : "MSG-246",
 "message" : "Sending SMS from/to extension numbers is not available"
}.
```
We should not call SMS API request given the toNumber is invalid.

**Comment by embbnux** [comment]
I will fix it soon

**Comment by embbnux** [comment]
there are some to numbers errors that can be found only after call SMS API.
And I find a bug that if ClientHistoryRequest object be created multiple, client will have repeat event on requestError. I will find some way to fix it so it can reduce error message.

**Comment by LingForCC** [comment]
@embbnux  Yes. You are right. We could not identify some of the invalid numbers in our side. Close the ticket.
