### ISSUE TITLE
Implement general Error mechanism

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-integration-commons#21]
Implement a general Error mechanism so lib could provide meaningful error to lib consumers.

**Comment by u9520107** [comment]
Current design for errors is as such:
1. The module itself doesn't retain the module in its state. We've found that there is simply no use case for the error objects to keep it in state.
2. The module would send a message item into Alert module, errors can be passed as a payload. The Alert module works similarly to a notification tab, it will keep the message in the state for a default amount of time before discarding them. Unless the module specified that the message should not be automatically discarded. It is then up to UI components to display the message in the Alert module.
3. Ideally, we maintain alert message enums to be passed around as the alert message.
