### ISSUE TITLE
Event emitter in RcPhone

### ISSUE THREAD

**Issue by changbenny** [ringcentral/ringcentral-js-integration-commons#25]
For now, only user module implement Emitter. Is it needed to be generalized into RcPhone?
One use case is that I want to listen when the login success.

**Comment by u9520107** [comment]
Originally I want each module to manage their own events. What you need can be achieved with two different solutions:
1. Each module has their own emitter, then rcPhone create a emitter object as well and relay the event.
2. RcPhone create a emitter object that is passed into other modules as dependencies.

I think solution 2 is probably a cleaner and lighter solution. What do you guys think?

**Comment by changbenny** [comment]
After discussion, we go for solution 2.
