### ISSUE TITLE
A simpler way to create a root module

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-integration-commons#326]
Now, we need to create a root module such as Phone module using this code [Phone.js](https://github.com/ringcentral/ringcentral-js-integration-commons/blob/master/dev-server/Phone.js)

Maybe, we can create a simple way to generate a Phone module.
It can resolve dependences of each module automatically.
It does not care about the sequence of modules.
It uses less code.

**Comment by u9520107** [comment]
@embbnux Agreed! I've been thinking about that a while ago, but it was not an urgent issue so I put that aside. Perhaps you can brainstorm with some others who are interested and let's discuss about it.

**Comment by embbnux** [comment]
updated with #422
