### ISSUE TITLE
Please update doc about creating modules

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-integration-commons#340]
![image](https://user-images.githubusercontent.com/733544/28624388-971bcbd0-724b-11e7-9220-1dae2b307bb2.png)

`Typical Folder Structure` doesn't exist at all:

![image](https://user-images.githubusercontent.com/733544/28624403-9cd110d0-724b-11e7-8009-4d58881e9e60.png)

`DialingPlan` is not a good example any more.

**Comment by embbnux** [comment]
document updated
