### ISSUE TITLE
Export status enum

### ISSUE THREAD

**Issue by changbenny** [ringcentral/ringcentral-js-integration-commons#40]
widgets layer need to compare state in redux store with status enum. Such as:
`state.user.status === 'LOGGED_IN'`
Should be
`state.user.status === phone.user.LOGGED_IN`

In the widgets layer we also need to provide a way to pass those enum.

**Comment by u9520107** [comment]
Good point...
Which do you think is better? 
1. `phone.enums.loginStatus.loggedIn`
2. `phone.user.enums.status.loggedIn`
3. `phone.user.enums.loginStatus.loggedIn` ?

**Comment by changbenny** [comment]
After discussion, we go for solution 3.
